Select  AKD_TPSALD, format(SUM(AKD_VALOR1),'N','pt-br')    AS nTotal2,AKD_FILIAL from AKD010 (NOLOCK)
WHERE D_E_L_E_T_ =  ' ' AND
(AKD_PROCES = '000054' OR AKD_PROCES = '000252')  AND
AKD_FILIAL = '010005' AND
AKD_CO = '1104010001' AND
AKD_CC = '09002' AND
AKD_CODPLA =  'ORC_BRCT' AND
AKD_VERSAO = '0001' AND
AKD_DATA>= '20170101' AND
AKD_DATA<= '20170831'
GROUP BY AKD_TPSALD, AKD_FILIAL

SELECT * FROM AKD010
WHERE D_E_L_E_T_ =  ' ' 

SELECT 
 DISTINCT 
  ZAZ_ITEMCC AS POLITICA,
  F1_FILIAL AS  FILIAL,
  F1_DOC AS  DOC,
  F1_SERIE AS  SERIE,
  F1_FORNECE AS  FORNECE,
  F1_LOJA AS LOJA,
  A2_NOME AS NOME,
  F1_XBLQFIS AS SITFIS,
  COALESCE(ZB1_DTPREV,'-') AS DTPREVREC,
  COALESCE(ZB1_DTREC,'-') AS DTCONFREC,
  CASE 
   WHEN ZAZ_STATUS = '1' THEN 'SIM'
   WHEN ZAZ_STATUS = '2' THEN 'NAO'
   ELSE ''
  END AS INTWMS,
  CASE 
   WHEN ZAZ_STATUS = '2' THEN 'BRASILCT'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') <> '' AND COALESCE(ZB1_DTREC,'') = '' THEN 'BRASILCT'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') <> '' AND COALESCE(ZB1_DTREC,'') <> '' THEN 'BRASILCT'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') = '' THEN 'WMS'
   ELSE ''
  END AS [PENDENTE],
  CASE 
   WHEN ZAZ_STATUS = '2' THEN 'FALHA INT.WMS'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') <> '' AND COALESCE(ZB1_DTREC,'') = '' THEN 'CONF.LOGISTICA'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') <> '' AND COALESCE(ZB1_DTREC,'') <> '' THEN 'AGUARD.CLASS.'
   WHEN ZAZ_STATUS = '1' AND COALESCE(ZAT_DOC,'') = '' THEN 'AGUARD.WMS'
   ELSE ''
  END AS SITUACAO
FROM SF1010 (NOLOCK) SF1
INNER JOIN SA2010 (NOLOCK) SA2 ON
 F1_FORNECE = A2_COD 
 AND F1_LOJA = A2_LOJA
 AND SA2.D_E_L_E_T_=''
LEFT JOIN ZB1010 (NOLOCK) ZB1 ON
 F1_FILIAL = ZB1_FILIAL
 AND F1_DOC = ZB1_DOC
 AND F1_SERIE =  ZB1_SERIE
 AND F1_FORNECE = ZB1_FORNEC
 AND F1_LOJA = ZB1_LOJA
 AND F1_TIPO = ZB1_TIPO
 AND ZB1.D_E_L_E_T_=''
INNER JOIN ZAZ010 (NOLOCK) ZAZ ON
 F1_FILIAL + F1_DOC + F1_SERIE + F1_FORNECE + F1_LOJA + F1_TIPO = ZAZ_CHVSF1
 AND ZAZ_CHVSF1 <> ''
 --AND ZAZ_ITEMCC='AVN0002'
 AND SF1.D_E_L_E_T_=''
LEFT JOIN ZAT010 (NOLOCK) ZAT ON
 F1_FILIAL = ZAT_FILIAL
 AND F1_DOC = ZAT_DOC
 AND F1_SERIE =  ZAT_SERIE
 AND F1_FORNECE = ZAT_FORNEC
 AND F1_LOJA = ZAT_LOJA
 AND F1_TIPO = ZAT_TIPO
 AND ZAT.D_E_L_E_T_=''
WHERE
 SF1.D_E_L_E_T_=''
 AND F1_STATUS=''
 AND F1_XBLQFIS='L'
 
 coluna DTCONFREC VAZIA ==> LOGISTICA DO CD NÃO CONFIRMOU A NF
 coluna SITUACAO AGUARDA.WMS  ==> AGUARDA CONFIRMACAO NF